#if !defined  (__headers_h)
#define __headers_h

#	if!defined  (__fstream_h)
#	include	  <fstream.h>
#endif
#	if !defined (__conio_h)
#	include      <conio.h>
#endif
#	if!defined (__iostream_h)
#	include      <iostream.h>
#endif
#	if !defined (__stdio_h)
#	include      <stdio.h>
#endif
#	if !defined (__stdlib_h)
#	include      <stdlib.h>
#endif
#	if !defined (__fcntl_h)
#	include      <fcntl.h>
#endif
#	if !defined (__io_h)
#	include      <io.h>
#endif
#	if !defined (__dos_h)
#	include      <dos.h>
#endif
#	if !defined (__values_h)
#	include      <values.h>
#endif
 #endif